# Generated by Django 4.1.2 on 2022-11-03 10:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1', models.CharField(max_length=16)),
                ('amenity', models.CharField(max_length=8)),
                ('healthcare', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=81)),
                ('ref', models.CharField(max_length=4)),
                ('fid', models.CharField(max_length=16)),
                ('addr_city', models.CharField(max_length=17)),
                ('addr_postc', models.CharField(max_length=6)),
                ('emergency', models.CharField(max_length=3)),
                ('addr_distr', models.CharField(max_length=10)),
                ('addr_full', models.CharField(max_length=66)),
                ('addr_state', models.CharField(max_length=6)),
                ('source', models.CharField(max_length=18)),
                ('website', models.CharField(max_length=42)),
                ('healthca_1', models.CharField(max_length=31)),
                ('building', models.CharField(max_length=3)),
                ('survey_dat', models.CharField(max_length=10)),
                ('addr_house', models.CharField(max_length=28)),
                ('addr_stree', models.CharField(max_length=42)),
                ('note', models.CharField(max_length=85)),
                ('operator', models.CharField(max_length=43)),
                ('phone', models.CharField(max_length=16)),
                ('wheelchair', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=32)),
                ('opening_ho', models.CharField(max_length=4)),
                ('name_en', models.CharField(max_length=55)),
                ('fax', models.CharField(max_length=7)),
                ('internet_a', models.CharField(max_length=4)),
                ('contact_ph', models.CharField(max_length=27)),
                ('operator_t', models.CharField(max_length=10)),
                ('descriptio', models.CharField(max_length=27)),
                ('office', models.CharField(max_length=23)),
                ('wikidata', models.CharField(max_length=9)),
                ('addr_place', models.CharField(max_length=9)),
                ('short_name', models.CharField(max_length=6)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('complaint', models.TextField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
