# Generated by Django 4.1.2 on 2022-11-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='id_1',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
