# Generated by Django 4.1.2 on 2022-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0002_alter_export_id_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='addr_city',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='addr_distr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='addr_full',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='addr_house',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='addr_place',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='addr_postc',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='addr_state',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='addr_stree',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='amenity',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='building',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='contact_ph',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='descriptio',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='emergency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='fax',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='fid',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='healthca_1',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='healthcare',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='internet_a',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='name',
            field=models.CharField(blank=True, max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='name_en',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='note',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='office',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='opening_ho',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='operator',
            field=models.CharField(blank=True, max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='operator_t',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='ref',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='short_name',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='source',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='survey_dat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='website',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='wheelchair',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='wikidata',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
