# Generated by Django 4.1.2 on 2022-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0003_alter_export_addr_city_alter_export_addr_distr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=81, null=True),
        ),
    ]
