# Generated by Django 4.1.2 on 2022-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0004_alter_export_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='name',
            field=models.CharField(blank=True, default='no_name', max_length=81, null=True),
        ),
    ]
