# Generated by Django 4.1.2 on 2022-11-07 06:36

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path
DATA_FILENAME = 'export.json'
def load_data(apps, schema_editor):
    incidence = apps.get_model('hotspot', 'incidence')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile),encoding='UTF-8') as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    incidence(name=name, location = location).save()
            except KeyError:
                pass     

class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0005_alter_export_name'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
