# Generated by Django 4.1.2 on 2022-11-08 09:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0006_auto_20221107_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='#1DB03C', srid=4326),
        ),
    ]
