# Generated by Django 4.1.2 on 2022-11-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0007_alter_incidence_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='addr_full',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='id_1',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='website',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
